# Generated by Django 4.2.18 on 2025-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mood',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
